version: '3.5'

services:

  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    command: npm run server

  client:
    build: ./client
    expose:
      - ${REACT_APP_PORT}
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    links:
      - server
    command: npm start
